# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestValidacinlistado():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_validacinlistado(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(697, 720)
    self.driver.find_element(By.CSS_SELECTOR, ".active > .nav-link").click()
    assert self.driver.find_element(By.ID, "itemc").text == "Phones"
    assert self.driver.find_element(By.LINK_TEXT, "Laptops").text == "Laptops"
    assert self.driver.find_element(By.LINK_TEXT, "Monitors").text == "Monitors and accessories"
  
