# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCampos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_campos(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(697, 720)
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#exampleModal .form-group:nth-child(1) > .form-control-label").text == "Contact Email:"
    assert self.driver.find_element(By.CSS_SELECTOR, "#exampleModal .form-group:nth-child(2) > .form-control-label").text == "Contact Name:"
    assert self.driver.find_element(By.CSS_SELECTOR, "#exampleModal .form-group:nth-child(3) > .form-control-label").text == "Message:"
    element = self.driver.find_element(By.ID, "recipient-email")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "recipient-name")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "message-text")
    assert element.is_enabled() is True
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#exampleModal .btn-secondary")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#exampleModal .btn-primary")
    assert len(elements) > 0
  
